export const DEPARTMENTS = [
  'Anatomy',
  'Anesthesiology',
  'Biochemistry',
  'Community Medicine',
  'Dermatology, Venereology & Leprosy',
  'Emergency Medicine',
  'ENT',
  'Forensic Medicine',
  'General Medicine',
  'General Surgery',
  'Microbiology',
  'OBG',
  'Ophthalmology (Eye)',
  'Orthopaedics',
  'Otorhinolaryngology (ENT)',
  'Paediatrics',
  'Pathology',
  'Pharmacology',
  'Physiology',
  'Psychiatry',
  'Radiation Oncology',
  'Radio-diagnosis (Radiology)',
  'Respiratory Medicine',
];
